---
name: App-ZofCMS-Plugin-SplitPriceSelect
version: 0.0103
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin for generating a <select> for "price range" out of arbitrary range of prices.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0102
  HTML::Template: 2.9
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::SplitPriceSelect:
    file: lib/App/ZofCMS/Plugin/SplitPriceSelect.pm
    version: 0.0103
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
